name: Publish a snapshot release

on:
  push:
    branches:
      - master

jobs:
  publish_snapshot:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d
        with:
          distribution: 'zulu'
          java-version: 11

      - uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Setup Gradle
        uses: gradle/gradle-build-action@fd32ae908111fe31afa48827bd1ee909540aa971
        with:
          gradle-version: wrapper

      - name: Publish the artifacts
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
        run: ./gradlew :uri:publishAllPublicationsToMavenCentralRepository

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx4g -Xms128m -XX:MaxPermSize=4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"
